version: 0.2

environment_variables:
  plaintext:
    CONFIG_FILE: env-details.yml

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade pip
      - pip install --upgrade typing
      - pip install --upgrade awscli
      - pip install --upgrade boto3 
      - pip install --upgrade pyyaml 
      - pip install --upgrade yamllint
  pre_build:
    commands:
      - echo "Validating config file $CONFIG_FILE"
      - yamllint $CONFIG_FILE
  build:
    commands:
      - echo "Validating resources..."
      - python validate-env.py
      - exit $?
